using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;

public class UIEventHandler : MonoBehaviour, IPointerClickHandler, IPointerDownHandler, IPointerUpHandler, IBeginDragHandler, IEndDragHandler, IDragHandler
{
    public Action OnClickHandler = null;
    public Action OnPressedHandler = null;
    public Action OnPointerDownHandler = null;
    public Action OnPointerUpHandler = null;
    public Action<PointerEventData> OnDragHandler = null;
    public Action<PointerEventData> OnBeginDragHandler = null;
    public Action<PointerEventData> OnEndDragHandler = null;

    private bool isPressed = false;
    private void Update()
    {
        if (isPressed)
            OnPressedHandler?.Invoke();
    }
    public void OnPointerClick(PointerEventData _eventData)
    {
        OnClickHandler?.Invoke();
    }

    public void OnBeginDrag(PointerEventData _eventData)
    {
        OnBeginDragHandler?.Invoke(_eventData);
    }


    public void OnEndDrag(PointerEventData _eventData)
    {
        OnEndDragHandler?.Invoke(_eventData);
    }

    public void OnDrag(PointerEventData _eventData)
    {
        isPressed = true;
        OnDragHandler?.Invoke(_eventData);
    }

    public void OnPointerDown(PointerEventData _eventData)
    {
        isPressed = true;
        OnPointerDownHandler?.Invoke();
    }

    public void OnPointerUp(PointerEventData _eventData)
    {
        isPressed = true;
        OnPointerUpHandler?.Invoke();
    }
}
